---
name: system-usage
on:
  workflow_dispatch:
  
jobs:

details:
  run-on: ubuntu-latest
  steps:
    - name: check disk
      run: echo df -h
      
    - name: check memory
      run: echo free -m

